[package]
name = "bp-monitor"
version = "1.1.0"
edition = "2021"

[dependencies]
bp-core = { path = "../bp-core" }
bincode = "1.3.3"
tokio = { version = "1.8.2", features = ["net", "macros"] }
serde = { version = "1.0", features = ["derive"] }
