[package]
name = "bp-monitor"
version = "1.1.0"
edition = "2021"

[dependencies]
bp-core = { path = "../bp-core" }

### network
bytes = "1.0.1"
tokio = { version = "1.8.2", features = [] }

### logging
log = "0.4.0"
