[package]
name = "bp-monitor"
version = "2.0.0-alpha.3"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
async-trait = "0.1.50"
bincode = "1.3.3"
tokio = { version = "1.8.2", features = ["net", "macros"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.68"
