[package]
name = "bp"
version = "0.1.0"
authors = ["Micooz Lee <micooz@hotmail.com>"]
description = "bp is a lightweight and efficient proxy written in pure Rust."
repository = "https://github.com/micooz/bp"
readme = "README.md"
keywords = ["bp", "proxy", "socks", "socks5", "firewall"]
license = "MIT"
edition = "2018"

[[bin]]
name = "bp"
path = "bin/bp.rs"

[dependencies]
async-trait = "0.1.50"
bytes = "1.0.1"
chacha20poly1305 = "0.8.1"
dirs = "3.0.2"
dyn-clone = "1.0.4"
env_logger = "0.9.0"
hkdf = "0.11.0"
humantime = "2.1.0"
log = "0.4.0"
rand = { version = "0.8.4", features = ["std_rng"] }
sha2 = "0.9.5"
tokio = { version = "1.10.0", features = ["rt-multi-thread", "net", "sync", "io-util", "time"] }

[dependencies.clap]
version = "3.0.0-beta.2"
default-features = false
features = ["std", "derive", "cargo"]
