// This file is automatically generated.

function FindProxyForURL(url, host) \{
  // extract port number from url
  var port_match = url.match(/:(\d\{0,5})/);
  var port = port_match[1] ? Number(port_match[1]) : null;

{if_statements}

  return "DIRECT";
}
