[package]
name = "e2e"
version = "1.1.2"
edition = "2021"

[dependencies]
bp-core = { path = "../bp-core" }
bp-cli = { path = "../bp-cli" }
cmd_lib = "1.2.4"
httpmock = "0.6.2"
lazy_static = "1.4.0"
tokio = { version = "1.8.2", features = ["rt-multi-thread", "macros"] }
