[package]
name = "bp-cli"
version = "1.0.0-alpha.0"
edition = "2018"

[dependencies]
bp-core = { path = "../bp-core" }
bp-monitor = { path = "../bp-monitor" }
lazy_static = "1.4.0"
tokio = { version = "1.8.2", features = ["rt-multi-thread", "macros"] }
dirs = "4.0.0"
env_logger = "0.9.0"
humantime = "2.1.0"
log = "0.4.0"
# syslog = "5.0.0"

[dev-dependencies]
bp-test = { path = "../bp-test" }
bytes = "1.0.1"
cmd_lib = "1.3.0"
