[package]
name = "bp-cli"
version = "1.1.2"
edition = "2021"

[features]
profile = [
  # "jemallocator",
  # "jemalloc-ctl",
  # "jemalloc-sys",
]

[dependencies]
bp-core = { path = "../bp-core" }
anyhow = "1.0.44"
daemonize = "0.4.1"
dirs = "4.0.0"
lazy_static = "1.4.0"
log4rs = { version = "1.0.0", features = ["gzip"] }
log = "0.4.0"
tokio = { version = "1.16.1", features = ["rt-multi-thread", "macros"] }
parking_lot = "0.11.2"
signal-hook = "0.3.10"
dhat = "0.3.0"
# jemallocator = { version = "0.3.2", optional = true }
# jemalloc-ctl = { version = "0.3.2", optional = true }
# jemalloc-sys = { version = "0.3.2", optional = true, features = ["stats", "profiling", "unprefixed_malloc_on_supported_platforms"] }
