[package]
name = "bp-cli"
version = "1.0.0-alpha.0"
edition = "2018"

[dependencies]
bp-core = { path = "../bp-core" }
bp-monitor = { path = "../bp-monitor" }
dirs = "4.0.0"
lazy_static = "1.4.0"
log4rs = "1.0.0"
anyhow = "1.0.44"
log = "0.4.0"
tokio = { version = "1.8.2", features = ["rt-multi-thread", "macros"] }
# trust-dns-resolver = { version = "0.20.3", features = ["dns-over-tls", "dns-over-rustls"]}
trust-dns-resolver = { version = "0.20.3" }

[dev-dependencies]
bp-test = { path = "../bp-test" }
bytes = "1.0.1"
cmd_lib = "1.2.4"
