// This file is automatically generated.

function FindProxyForURL(url, host) {
  // skip example.com
  if (shExpMatch(host, "*example2.com*")) return "PROXY 127.0.0.1:1080";
  if (shExpMatch(host, "example1.com")) return "DIRECT";
  if (shExpMatch(host, "example.com")) return "PROXY 127.0.0.1:1080";

  return "DIRECT";
}
