name: Build & Test (Self Hosted)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: "trace"
  RUST_BACKTRACE: full

jobs:
  build-test-check:
    strategy:
      matrix:
        platform:
          - self-hosted
          # - ubuntu-latest
          # - windows-latest
          # - macos-latest
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: clippy

      - name: Build & Test (Default)
        run: cargo test --workspace --verbose --no-fail-fast

      - name: Clippy Check
        uses: actions-rs/clippy-check@v1
        with:
          name: clippy-${{ matrix.platform }}
          token: ${{ secrets.GITHUB_TOKEN }}
          args: |
            --verbose -- -Z macro-backtrace
